- name: variables from a file
  vars_files: Variables.yaml
  hosts: mongodb

  tasks:
  - name: printing variables from a file
    ansible.builtin.debug:
      msg: " Hello I am learning {{COURSE}} trainer is {{TRAINER}} and course duration is {{DURATION}}"