- name: printing variables from inventory files
  hosts: mongodb
  
  tasks:
  - name: printing variables
    ansible.builtin.debug:
      msg: "Mongo username is {{MONGODB_UNAME}} and DB is {{MONGO_DB}}"