- name: simple condition
  hosts: localhost
  vars:
    NAME: Devops

  tasks:
  - name: print something if condition is true
    when: NAME == "Devops"
    ansible.builtin.debug:
      msg: The name is {{NAME}}