- name: loops
  hosts: localhost

  tasks:
  - name: print the names using loops
    ansible.builtin.debug:
      msg: "Hello {{item}}"
    # loop:   # To loop the each name
    # - naga
    # - babu
    # - raja
    # - linitha
    with_sequence: # to get the sequence in the range 1 to 10 including both
      - "1-10"