
- name: install packages using loop
  hosts: all

  tasks:
    - name: install a packages
      become: yes
      ansible.builtin.yum:
        name: "{{item}}"
        state: installed
      loop:
      - nginx
      - postfix

