- name: advanced loop concept
  hosts: mongodb
  become: yes

  tasks:
  - name: install/remove packages
    ansible.builtin.yum:
    name: "{{item.name}}"
    state: "{{item.state}}"

    loop:
    - {name: nginx, state: installed }
    - {name: postfix, state: absent}
  